name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 10 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Build
      run: npm run build

    - uses: actions/upload-artifact@master
      with:
        name: dist-build
        path: dist

  check-features:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: dist-build
          path: dist

      - name: install
        run: npm install

      - name: Check
        run: npm run check

  test-sweary:
    needs: check-features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: dist-build
          path: dist

      - name: install
        run: npm install

      - name: Run tests
        run: tags=@sweary npm run filter-test

  test-notsweary:
    needs: check-features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: dist-build
          path: dist

      - name: install
        run: npm install

      - name: Run tests
        run: tags=@notsweary npm run filter-test

  test-all:
    needs: [ test-sweary, test-notsweary ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: dist-build
          path: dist

      - name: install
        run: npm install

      - name: Run tests
        run: npm run test