on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 10 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Build
      run: yarn build

    - uses: actions/upload-artifact@master
      with:
        name: dist-build
        path: dist

  check-features:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: dist-build
          path: dist

      - name: check-dist
        run: ls dist

      - name: Check
        run: cucumber-js dist/features/ --dry-run

  test-sweary:
    needs: check-features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: dist-build
          path: dist

      - name: check-dist
        run: ls dist

      - name: Check
        run: cucumber-js dist/features/ --tags=@sweary

  test-notsweary:
    needs: check-features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: dist-build
          path: dist

      - name: check-dist
        run: ls dist

      - name: Check
        run: cucumber-js dist/features/ --tags=@notsweary

  test-all:
    needs: [ test-sweary, test-notsweary ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: dist-build
          path: dist

      - name: check-dist
        run: ls dist

      - name: Check
        run: cucumber-js dist/features/