on:
  push:
    branches:    
      - main

  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 10 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Build
      run: npm install
    - name: test
      run: npm test