on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 10 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Build
      run: yarn build

    - uses: actions/upload-artifact@master
      with:
        name: dist-build
        path: dist